### ISSUE TITLE
Update API documentation for multiple subtractions

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-website#116]
Update changed endpoints:

`GET /api/analyses/:id`
`POST /api/samples/:id/analyses`
`GET /api/samples/:id/analyses`

**Comment by tianshengsui** [comment]
@igboyes This endpoint `POST /api/analyses/:id` doesn't exist. Do you mean `POST /api/samples/:id/analyses` ?

**Comment by igboyes** [comment]
Oops. Yes @tianshengsui.
