### ISSUE TITLE
Analysis documentation

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-website#38]
Add the following sections:
- list analyses for sample
- create analysis (link to quick analyze docs)
- delete analysis
- move **Analysis Jobs** and **Caching** to overview main section

**Comment by mdhaul** [comment]
I'm finished making the changes you assigned but GitKraken won't let me push. It's telling me access denied. The message looks like this:

![push failed](https://user-images.githubusercontent.com/59845526/73582828-c9f51080-4443-11ea-9a88-815fb4d13677.png)

**Comment by igboyes** [comment]
Hi. We pushed this branch, but you still need to make a PR for it.

**Comment by mdhaul** [comment]
For some reason its not giving me an option to make a pull request like we've done in the past :(  If I go under PR its only lists "Subtraction User Guide"
